### ISSUE TITLE
Secret key used for token generation stored insecurely

### ISSUE THREAD

**Issue by ss14635** [CSGY-9223-Group1/lab-1#8]
## Issue Description

In the application, authentication is done by providing a token that is generated and associated uniquely with each user. However, the secret key used during token generation is hard-coded and stored in plaintext in the `main.py` file on line 15. This is used in the `register` function on line 54 along with the unique user `id` to create a token derived from a JWT (JSON Web Token).  

The encoded token is composed of three parts: 

- the header, which contains the algorithm type (HS256) and token type (JWT)
- the JSON payload content, which in this case would contain the user `id`
- the signature, which contains the secret key

The algorithm type and secret key are known by simply looking at the source code of `main.py`. All a bad actor would have to do is successfully guess a user's `id` to be able to also successfully recover their token using the JWT Debugger (available at jwt.io).

## Proposed Solution

A viable solution for this issue would be to use something like [Development Environment Secrets](https://docs.github.com/en/enterprise-cloud@latest/codespaces/managing-codespaces-for-your-organization/managing-development-environment-secrets-for-your-repository-or-organization) for Github Codespaces or alternatively, [Secrets](https://docs.github.com/en/enterprise-cloud@latest/actions/security-for-github-actions/security-guides/using-secrets-in-github-actions) in Github Actions. Both of these allow for repository secrets to be stored and used securely. Inside of the application, instead of having the secret hard-coded in plaintext, it would be hidden behind an environmental variable.

**Comment by rpyzh** [comment]
Thank you for reporting the issue! Working on it.

**Comment by rpyzh** [comment]
@ss14635 - please, take a look at PR #13 associated with this issue. If you feel like it did not fully address the issue you have raised, please, feel free to reopen the issue with additional comments.
